local menue0e4fc6213e8b3593495a7260c3a4c2e = {
  { 'Show Me The Key', '/usr/bin/showmethekey-gtk', '/usr/share/icons/hicolor/64x64/apps/one.alynx.showmethekey.png' },
}

local menu98edb85b00d9527ad5acebe451b3fae6 = {
  { 'AniTuner', 'anituner' },
  {
    'AppImageLauncher Settings',
    'AppImageLauncherSettings ',
    '/usr/share/icons/hicolor/16x16/apps/AppImageLauncher.png',
  },
  { 'Authme', 'authme', '/usr/share/icons/hicolor/32x32/apps/authme.png' },
  {
    'Bottles',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=bottles --file-forwarding com.usebottles.bottles @@u  @@',
  },
  { 'Bulk Rename', 'thunar --bulk-rename ', '/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png' },
  { 'Checkmate', 'checkmate', '///usr/share/icons/checkmate_icon.png' },
  { 'Drive-Mount', 'mount-gtk' },
  {
    'Flatseal',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=com.github.tchx84.Flatseal com.github.tchx84.Flatseal',
  },
  {
    'Flatsweep',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=flatsweep io.github.giantpinkrobots.flatsweep',
  },
  { 'Font Manager', 'font-manager ' },
  { 'Font Viewer', '/usr/lib/font-manager/font-viewer ' },
  { 'HP Device Manager', 'hp-toolbox', '///usr/share/hplip/data/images/128x128/hp_logo.png' },
  { 'Helix', 'xterm -e kitty -e hx ', '///usr/share/icons/Helix.png' },
  { 'Icon picker', 'nwg-icon-picker', '/usr/share/pixmaps/nwg-icon-picker.svg' },
  { 'KeePassXC', 'keepassxc ', '/usr/share/icons/hicolor/256x256/apps/keepassxc.png' },
  { 'Keyboard layout viewer', 'kbd-layout-viewer5' },
  { 'Kvantum Manager', 'kvantummanager' },
  { 'Lan Mouse', 'lan-mouse' },
  {
    'LocalSend',
    'env DESKTOPINTEGRATION=false /usr/bin/localsend',
    '/usr/share/icons/hicolor/128x128/apps/localsend.png',
  },
  { 'LocalSend', 'localsend ', '/usr/share/icons/hicolor/128x128/apps/localsend.png' },
  { 'Neovim', 'xterm -e nvim ', '///home/hebedite/.local/share/icons/Gruvbox-Plus-Dark/apps/scalable/nvim.svg' },
  { 'OpenRGB', 'openrgb', '/usr/share/icons/hicolor/128x128/apps/OpenRGB.png' },
  { 'OrcaSlicer', '/home/hebedite/Applications/OrcaSlicer_Linux_AppImage_V2.3.0-dev.AppImage ' },
  {
    'PeaZip',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=peazip --file-forwarding io.github.peazip.PeaZip @@  @@',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/256x256/apps/io.github.peazip.PeaZip.png',
  },
  { 'Piper', 'piper' },
  { 'ProtonUp-Qt', 'net.davidotek.pupgui2', '/usr/share/icons/hicolor/64x64/apps/net.davidotek.pupgui2.png' },
  { 'Protontricks', 'protontricks --no-term --gui' },
  { 'Qalculate! (Qt)', 'qalculate-qt', '/usr/share/icons/hicolor/16x16/apps/qalculate-qt.png' },
  {
    'SeamlyMe',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=seamlyme --file-forwarding io.seamly.seamly2d @@  @@',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/64x64/apps/io.seamly.seamly2d.seamlyme.png',
  },
  { 'Show Me The Key', '/usr/bin/showmethekey-gtk', '/usr/share/icons/hicolor/64x64/apps/one.alynx.showmethekey.png' },
  { 'Solaar', 'solaar' },
  { 'Stacer', 'stacer', '/usr/share/icons/hicolor/16x16/apps/stacer.png' },
  { 'UltiMaker Cura (5.9.0)', '/home/hebedite/Applications/UltiMaker-Cura-5.9.0-linux-X64.AppImage' },
  { 'VSCodium', '/usr/bin/codium --unity-launch ', '/usr/share/pixmaps/vscodium.png' },
  {
    'VSCodium - Wayland',
    '/usr/bin/codium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland ',
    '/usr/share/pixmaps/vscodium.png',
  },
  { 'Variety', 'variety ' },
  { 'Ventoy', 'ventoygui', '/usr/share/pixmaps/ventoy.png' },
  { 'Vim', 'xterm -e vim ', '///home/hebedite/.local/share/icons/Gruvbox-Plus-Dark/apps/scalable/vim.svg' },
  { 'Waypaper', 'waypaper' },
  { 'Winetricks', 'winetricks --gui' },
  { 'XColor', 'xcolor -s', '/usr/share/icons/hicolor/16x16/apps/xcolor.png' },
  { 'Xarchiver', 'xarchiver ', '/usr/share/icons/hicolor/16x16/apps/xarchiver.png' },
  { 'Zim Desktop Wiki', 'zim ', '/usr/share/icons/hicolor/16x16/apps/org.zim_wiki.Zim.png' },
  { 'ipython', 'xterm -e ipython' },
  { 'picom', 'picom' },
  { 'scrcpy', '/bin/sh -c "\\$SHELL -i -c scrcpy"', '/usr/share/icons/hicolor/256x256/apps/scrcpy.png' },
  {
    'scrcpy (console)',
    'xterm -e /bin/sh -c "\\$SHELL -i -c \'scrcpy --pause-on-exit=if-error\'"',
    '/usr/share/icons/hicolor/256x256/apps/scrcpy.png',
  },
  { 'xppentablet', '/usr/lib/pentablet/PenTablet.sh', '///usr/share/icons/hicolor/256x256/apps/xppentablet.png' },
}

local menude7a22a0c94aa64ba2449e520aa20c99 = {
  { 'Decker', 'decker' },
  { 'Drumstick ALSA MIDI Player', 'drumstick-guiplayer ', '/usr/share/icons/hicolor/16x16/apps/drumstick.png' },
  { 'Drumstick Drum Grid', 'drumstick-drumgrid', '/usr/share/icons/hicolor/16x16/apps/drumstick.png' },
  { 'Drumstick Virtual Piano', 'drumstick-vpiano', '/usr/share/icons/hicolor/16x16/apps/drumstick.png' },
  {
    'FreeCAD',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=FreeCAD --file-forwarding org.freecad.FreeCAD - --single-instance @@  @@',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/16x16/apps/org.freecad.FreeCAD.png',
  },
  { 'LibreOffice Math', 'libreoffice --math ', '/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png' },
  { 'Qalculate! (Qt)', 'qalculate-qt', '/usr/share/icons/hicolor/16x16/apps/qalculate-qt.png' },
  {
    'SimulIDE',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=simulide com.simulide.simulide',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/256x256/apps/com.simulide.simulide.png',
  },
  { 'VMPK', 'vmpk', '/usr/share/icons/hicolor/16x16/apps/vmpk.png' },
}

local menu251bd8143891238ecedc306508e29017 = {
  { 'Crescent Loom', 'env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/9' },
  {
    'Incredipede',
    'env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/8',
    '///home/hebedite/.local/git/gruvbox-plus-icon-pack/Gruvbox-Plus-Dark/apps/scalable/Incredipede.svg',
  },
  { 'Lutris', 'lutris ', '/usr/share/icons/hicolor/16x16/apps/lutris.png' },
  { 'Pocket Kitten', 'env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/7' },
  { 'ProtonUp-Qt', 'net.davidotek.pupgui2', '/usr/share/icons/hicolor/64x64/apps/net.davidotek.pupgui2.png' },
  {
    'Steam',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam --file-forwarding com.valvesoftware.Steam @@u  @@',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/16x16/apps/com.valvesoftware.Steam.png',
  },
  { 'Textreme 2', 'env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/6' },
  { 'Thrive', 'env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/15' },
  { 'itch.io', '/opt/kitch/kitch ', '///home/hebedite/.local/share/icons/Gruvbox-Plus-Dark/apps/scalable/itch.svg' },
  { 'kitch', '/opt/kitch/kitch ', '/usr/share/icons/hicolor/32x32/apps/kitch.png' },
  { 'picoSYNTH', 'env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/1' },
}

local menud334dfcea59127bedfcdbe0a3ee7f494 = {
  { 'AniTuner', 'anituner' },
  { 'Birdfont', 'birdfont ', '/usr/share/icons/hicolor/48x48/apps/birdfont.png' },
  { 'Blender', 'blender ' },
  { 'Blender Launcher V2', "'/usr/bin/Blender Launcher'" },
  {
    'Blockbench',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=blockbench-run --file-forwarding net.blockbench.Blockbench @@u  @@',
  },
  { 'Color Picker for Wayland', 'wl-color-picker', '/usr/share/icons/wl-color-picker.png' },
  { 'Decker', 'decker ', '/usr/share/icons/hicolor/32x32/apps/decker.png' },
  { 'Flameshot', '/usr/bin/flameshot', '/usr/share/icons/hicolor/48x48/apps/org.flameshot.Flameshot.png' },
  {
    'FontForge',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=fontforge --file-forwarding org.fontforge.FontForge @@u  @@',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/16x16/apps/org.fontforge.FontForge.png',
  },
  {
    'FontForge',
    'fontforge ',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/16x16/apps/org.fontforge.FontForge.png',
  },
  {
    'FontForge',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=fontforge --file-forwarding org.fontforge.FontForge @@u  @@',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/16x16/apps/org.fontforge.FontForge.png',
  },
  {
    'FreeCAD',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=FreeCAD --file-forwarding org.freecad.FreeCAD - --single-instance @@  @@',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/16x16/apps/org.freecad.FreeCAD.png',
  },
  { 'GIMP', 'gimp-2.10 ', '///home/hebedite/.local/share/icons/Gruvbox-Plus-Dark/apps/scalable/gimp.svg' },
  { 'GNU Image Manipulation Program', 'gimp-2.10 ', '/usr/share/icons/hicolor/16x16/apps/gimp.png' },
  { 'GlslViewer', 'xterm -e glslViewer  --msaa -e dynamic_shadows,on', '/usr/share/pixmaps/glslViewer.png' },
  { 'Glyphr Studio v2', '/usr/bin/firefoxpwa site launch 01J3TFR5KDTTE3D9GHAGE5J6BB --protocol ' },
  {
    'Illustrator CC',
    'bash /home/hebedite/.illustratorCC17/launcher/launcher.sh',
    '///home/hebedite/.illustratorCC17/launcher/AiIcon.png',
  },
  { 'Inkscape', 'inkscape ', '/usr/share/icons/hicolor/16x16/apps/org.inkscape.Inkscape.png' },
  { 'Krita', 'krita ', '/usr/share/icons/hicolor/16x16/apps/krita.png' },
  { 'Laigter', '/home/hebedite/Applications/Laigter-x86_64.AppImage' },
  { 'LibreOffice Draw', 'libreoffice --draw ', '/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png' },
  { 'Material Maker', 'material-maker', '/usr/share/icons/hicolor/64x64/apps/material-maker.png' },
  {
    'OpenSCAD',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=openscad --file-forwarding org.openscad.OpenSCAD @@  @@',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/48x48/apps/org.openscad.OpenSCAD.png',
  },
  { 'OpenSCAD', 'openscad ', '/usr/share/icons/hicolor/48x48/apps/openscad.png' },
  { 'Pixelorama', 'pixelorama', '/usr/share/icons/hicolor/256x256/apps/pixelorama.png' },
  {
    'Prusa GCode viewer',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=entrypoint --file-forwarding com.prusa3d.PrusaSlicer --gcodeviewer @@  @@',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/256x256/apps/com.prusa3d.PrusaSlicer.GCodeViewer.png',
  },
  {
    'PrusaSlicer',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=entrypoint --file-forwarding com.prusa3d.PrusaSlicer --single-instance-on-url @@u  @@',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/256x256/apps/com.prusa3d.PrusaSlicer.png',
  },
  { 'RawTherapee', 'rawtherapee ', '/usr/share/icons/hicolor/16x16/apps/rawtherapee.png' },
  { 'SLK_img2pixel', '/home/hebedite/Applications/SLK_img2pixel-x86_64.AppImage' },
  { 'Scribus', 'scribus ', '/usr/share/icons/hicolor/16x16/apps/scribus.png' },
  {
    'Seamly2D',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=seamly2d --file-forwarding io.seamly.seamly2d @@  @@',
  },
  { 'Upscayl', 'upscayl ', '/usr/share/pixmaps/org.upscayl.Upscayl.png' },
  {
    'Upscayl',
    'upscayl  --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations',
    '/usr/share/pixmaps/org.upscayl.Upscayl.png',
  },
  { 'Vulkan Caps Viewer', 'vulkanCapsViewer' },
  { 'XColor', 'xcolor -s', '/usr/share/icons/hicolor/16x16/apps/xcolor.png' },
}

local menuc8205c7636e728d448c2774e6a4a944b = {
  { 'Avahi SSH Server Browser', '/usr/bin/bssh' },
  { 'Avahi VNC Server Browser', '/usr/bin/bvnc' },
  { 'Firefox Nightly', '/usr/lib/firefox-nightly/firefox ', '/usr/share/icons/hicolor/16x16/apps/firefox-nightly.png' },
  { 'Fractal', 'fractal ' },
  { 'Fractal', 'fractal' },
  { 'Rclone Browser', 'rclone-browser', '/usr/share/icons/hicolor/32x32/apps/rclone-browser.png' },
  { 'Remote Viewer', 'remote-viewer ', '/usr/share/icons/hicolor/16x16/apps/virt-viewer.png' },
  { 'RustDesk', 'rustdesk ', '/usr/share/icons/hicolor/256x256/apps/rustdesk.png' },
  { 'Signal', 'signal-desktop -- ', '/usr/share/icons/hicolor/16x16/apps/signal-desktop.png' },
  {
    'Steam',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/bin/steam --file-forwarding com.valvesoftware.Steam @@u  @@',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/16x16/apps/com.valvesoftware.Steam.png',
  },
  { 'Telegram', 'telegram-desktop -- ', '/usr/share/icons/hicolor/16x16/apps/telegram.png' },
  { 'Telegram Desktop', 'telegram-desktop -- ', '/usr/share/icons/hicolor/16x16/apps/telegram.png' },
  { 'Tor Browser', 'torbrowser-launcher ', '/usr/share/icons/hicolor/128x128/apps/torbrowser.png' },
  {
    'Tor Browser Launcher Settings',
    'torbrowser-launcher --settings',
    '/usr/share/icons/hicolor/128x128/apps/torbrowser.png',
  },
  { 'Vesktop', '/usr/bin/vesktop ', '/usr/share/icons/hicolor/16x16/apps/vesktop.png' },
  { 'Vesktop', '/usr/bin/vesktop', '/usr/share/icons/hicolor/16x16/apps/vesktop.png' },
  { 'Waterfox', 'waterfox-g ', '/usr/share/icons/hicolor/16x16/apps/waterfox.png' },
  { 'Zen Browser', '/opt/zen-browser-bin/zen-bin ', '/usr/share/icons/hicolor/16x16/apps/zen-browser.png' },
  { 'qBittorrent', 'qbittorrent ', '/usr/share/icons/hicolor/16x16/apps/qbittorrent.png' },
}

local menudf814135652a5a308fea15bff37ea284 = {
  { 'Bookworm', 'com.github.babluboy.bookworm ' },
  { 'Calibre', 'calibre --detach ', '/usr/share/icons/hicolor/16x16/apps/calibre-gui.png' },
  { 'E-book editor', 'ebook-edit --detach ', '/usr/share/icons/hicolor/16x16/apps/calibre-ebook-edit.png' },
  { 'E-book viewer', 'ebook-viewer --detach ', '/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png' },
  { 'GPT4All Chat', 'sh -c "LD_LIBRARY_PATH=/opt/gpt4all-chat/lib /opt/gpt4all-chat/bin/gpt4all-chat"' },
  { 'LRF viewer', 'lrfviewer ', '/usr/share/icons/hicolor/16x16/apps/calibre-viewer.png' },
  { 'LibreOffice', 'libreoffice ', '/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png' },
  { 'LibreOffice Base', 'libreoffice --base ', '/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png' },
  { 'LibreOffice Calc', 'libreoffice --calc ', '/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png' },
  { 'LibreOffice Draw', 'libreoffice --draw ', '/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png' },
  { 'LibreOffice Impress', 'libreoffice --impress ', '/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png' },
  { 'LibreOffice Math', 'libreoffice --math ', '/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png' },
  { 'LibreOffice Writer', 'libreoffice --writer ', '/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png' },
  { 'Obsidian', '/usr/bin/obsidian ', '/usr/share/pixmaps/obsidian.png' },
  { 'Sigil', 'sigil ', '/usr/share/icons/hicolor/16x16/apps/sigil.png' },
  { 'Zathura', 'zathura ', '/usr/share/icons/hicolor/16x16/apps/org.pwmt.zathura.png' },
}

local menu6311ae17c1ee52b36e68aaf4ad066387 = {
  { 'MIDIVisualizer', 'MIDIVisualizer', '/usr/share/pixmaps/MIDIVisualizer.png' },
}

local menue6f43c40ab1c07cd29e4e83e4ef6bf85 = {
  {
    'Android Studio',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=android-studio-wrapper com.google.AndroidStudio',
  },
  { 'CMake', 'cmake-gui ', '/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png' },
  { 'Decker', 'decker' },
  { 'Electron 27', 'electron27 ', '/usr/share/pixmaps/electron27.png' },
  { 'Electron 32', 'electron32 ', '/usr/share/pixmaps/electron32.png' },
  { 'Electron 33', 'electron33 ', '/usr/share/pixmaps/electron33.png' },
  { 'FLUID', 'fluid ', '/usr/share/icons/hicolor/32x32/apps/fluid.png' },
  { 'Fritzing', 'env QT_AUTO_SCREEN_SCALE_FACTOR=0 Fritzing ', '/usr/share/pixmaps/fritzing.png' },
  { 'Glade', 'glade ' },
  { 'Godot Engine', 'godot ', '/usr/share/pixmaps/godot.svg' },
  { 'Icon Browser', 'yad-icon-browser', '/usr/share/icons/hicolor/16x16/apps/yad.png' },
  { 'Julia', 'xterm -e julia', '/usr/share/pixmaps/julia.svg' },
  { 'PixelAfterAll (0.0.5)', '/home/hebedite/Applications/PixelAfterAll-0.0.5.AppImage --no-sandbox ' },
  { 'Pragtical', 'pragtical ' },
  { 'Qt Assistant', 'assistant6', '/usr/share/icons/hicolor/128x128/apps/assistant.png' },
  { 'Qt Assistant', 'assistant', '/usr/share/icons/hicolor/128x128/apps/assistant.png' },
  {
    'Qt Creator',
    '/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=qtcreator --file-forwarding io.qt.QtCreator @@  @@',
    '/home/hebedite/.local/share/flatpak/exports/share/icons/hicolor/16x16/apps/io.qt.QtCreator.png',
  },
  { 'Qt D-Bus Viewer', 'qdbusviewer6', '/usr/share/icons/hicolor/128x128/apps/qdbusviewer.png' },
  { 'Qt Designer', 'designer ' },
  { 'Qt Linguist', 'linguist6 ', '/usr/share/icons/hicolor/128x128/apps/linguist.png' },
  { 'Qt Linguist', 'linguist ', '/usr/share/icons/hicolor/128x128/apps/linguist.png' },
  { 'Qt QDBusViewer ', 'qdbusviewer', '/usr/share/icons/hicolor/128x128/apps/qdbusviewer.png' },
  { 'Qt Widgets Designer', 'designer6 ', '/usr/share/icons/hicolor/128x128/apps/designer.png' },
  { 'SLK_img2pixel', '/home/hebedite/Applications/SLK_img2pixel-x86_64.AppImage' },
  { 'SuperCollider IDE', 'scide ' },
  { 'UserFeedback Console', 'UserFeedbackConsole' },
  { 'VSCodium', '/usr/bin/codium ', '/usr/share/pixmaps/vscodium.png' },
  { 'VSCodium', '/usr/bin/codium --unity-launch ', '/usr/share/pixmaps/vscodium.png' },
  {
    'VSCodium - Wayland',
    '/usr/bin/codium --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland ',
    '/usr/share/pixmaps/vscodium.png',
  },
  { 'Vulkan Caps Viewer', 'vulkanCapsViewer' },
  { 'Waycheck', 'waycheck' },
  { 'Zeal', 'zeal ', '/usr/share/icons/hicolor/16x16/apps/zeal.png' },
  { 'ipython', 'xterm -e ipython' },
}

local menu80d754c83abbbd4ef5d150904efcc86c = {
  { 'KiCad', 'kicad ', '/usr/share/icons/hicolor/16x16/apps/kicad.png' },
  { 'KiCad Gerber Viewer', 'gerbview ', '/usr/share/icons/hicolor/16x16/apps/gerbview.png' },
  { 'KiCad Image Converter', 'bitmap2component ', '/usr/share/icons/hicolor/16x16/apps/bitmap2component.png' },
  { 'KiCad PCB Calculator', 'pcb_calculator', '/usr/share/icons/hicolor/16x16/apps/pcbcalculator.png' },
  { 'KiCad PCB Editor (Standalone)', 'pcbnew ', '/usr/share/icons/hicolor/16x16/apps/pcbnew.png' },
  { 'KiCad Schematic Editor (Standalone)', 'eeschema ', '/usr/share/icons/hicolor/16x16/apps/eeschema.png' },
}

local menu52dd1c847264a75f400961bfb4d1c849 = {
  { 'A-Noise', 'anoise', '/usr/share/icons/hicolor/16x16/apps/anoise.png' },
  { 'Ardour', 'ardour8', '/usr/share/icons/hicolor/16x16/apps/ardour8.png' },
  { 'Audacious', 'audacious ', '/usr/share/icons/hicolor/48x48/apps/audacious.png' },
  { 'Audacity', 'env GDK_BACKEND=x11 UBUNTU_MENUPROXY=0 audacity ', '/usr/share/pixmaps/audacity.xpm' },
  {
    'Bitwig Studio',
    '/usr/bin/flatpak run --branch=master --arch=x86_64 --command=bitwig-studio com.bitwig.BitwigStudio',
    '/var/lib/flatpak/exports/share/icons/hicolor/48x48/apps/com.bitwig.BitwigStudio.png',
  },
  { 'Calf Plugin Pack for JACK', 'calfjackhost', '/usr/share/icons/hicolor/16x16/apps/calf.png' },
  { 'Cardinal', 'Cardinal' },
  { 'Carla', 'carla ', '/usr/share/icons/hicolor/16x16/apps/carla.png' },
  { 'Carla Control', 'carla-control ', '/usr/share/icons/hicolor/16x16/apps/carla-control.png' },
  { 'DeaDBeeF', 'deadbeef ', '/usr/share/icons/hicolor/16x16/apps/deadbeef.png' },
  { 'Drumstick ALSA MIDI Player', 'drumstick-guiplayer ', '/usr/share/icons/hicolor/16x16/apps/drumstick.png' },
  { 'Drumstick Drum Grid', 'drumstick-drumgrid', '/usr/share/icons/hicolor/16x16/apps/drumstick.png' },
  { 'Drumstick MIDI Monitor', 'kmidimon ', '/usr/share/icons/hicolor/48x48/apps/kmidimon.png' },
  { 'Drumstick Virtual Piano', 'drumstick-vpiano', '/usr/share/icons/hicolor/16x16/apps/drumstick.png' },
  { 'Easy Effects', 'easyeffects' },
  { 'Echomixer', 'echomixer', '/usr/share/icons/hicolor/48x48/apps/echomixer.png' },
  { 'Envy24 Control', 'envy24control', '/usr/share/icons/hicolor/48x48/apps/envy24control.png' },
  { 'GNOME Network Displays', 'gnome-network-displays' },
  { 'HDAJackRetask', 'hdajackretask' },
  { 'HDSPConf', 'hdspconf', '/usr/share/icons/hicolor/48x48/apps/hdspconf.png' },
  { 'HDSPMixer', 'hdspmixer', '/usr/share/icons/hicolor/48x48/apps/hdspmixer.png' },
  { 'Hwmixvolume', 'hwmixvolume', '/usr/share/icons/hicolor/48x48/apps/hwmixvolume.png' },
  { 'Hydrogen', 'hydrogen ' },
  { 'JamesDSP', 'jamesdsp', '/usr/share/pixmaps/me.timschneeberger.jdsp4linux.png' },
  { 'LMMS', 'lmms ', '/usr/share/icons/hicolor/16x16/apps/lmms.png' },
  { 'New Session Manager (Legacy GUI)', 'nsm-legacy-gui' },
  { 'OPL Synthesizer', 'opl-synth' },
  { 'Patchage', '/usr/bin/patchage' },
  { 'PulseAudio Volume Control', 'pavucontrol' },
  { 'QMidiRoute', 'qmidiroute' },
  { 'QjackCtl', 'qjackctl', '/usr/share/icons/hicolor/32x32/apps/org.rncbc.qjackctl.png' },
  { 'QmidiNet', 'qmidinet', '/usr/share/icons/hicolor/32x32/apps/org.rncbc.qmidinet.png' },
  { 'Qmmp', 'qmmp ', '/usr/share/icons/hicolor/16x16/apps/qmmp.png' },
  { 'Qt V4L2 test Utility', 'qv4l2', '/usr/share/icons/hicolor/16x16/apps/qv4l2.png' },
  { 'Qt V4L2 video capture utility', 'qvidcap', '/usr/share/icons/hicolor/16x16/apps/qvidcap.png' },
  { 'REAPER', '"/usr/lib/REAPER/reaper" ', '/usr/share/icons/hicolor/256x256/apps/cockos-reaper.png' },
  { 'Sonic Visualiser', 'sonic-visualiser ' },
  { 'Spotify (Launcher)', 'spotify-launcher ', '/usr/share/icons/hicolor/22x22/apps/spotify-launcher.png' },
  { 'Strawberry', 'strawberry ', '/usr/share/icons/hicolor/48x48/apps/strawberry.png' },
  { 'SuperCollider IDE', 'scide ' },
  { 'VCV Rack', 'vcvrack ', '/usr/share/pixmaps/vcvrack.png' },
  { 'VCV Rack', 'Rack', '/usr/share/pixmaps/vcvrack.png' },
  { 'VLC media player', '/usr/bin/vlc --started-from-file ', '/usr/share/icons/hicolor/16x16/apps/vlc.png' },
  { 'VMPK', 'vmpk', '/usr/share/icons/hicolor/16x16/apps/vmpk.png' },
  { 'Volume Control', 'pavucontrol' },
  { 'Xjadeo', 'xjadeo', '/usr/share/pixmaps/xjadeo.png' },
  { 'coppwr', 'coppwr', '/usr/share/icons/hicolor/32x32/apps/io.github.dimtpap.coppwr.png' },
  { 'mpv Media Player', 'mpv --player-operation-mode=pseudo-gui -- ', '/usr/share/icons/hicolor/16x16/apps/mpv.png' },
  { 'musikcube', 'xterm -e musikcube ' },
  { 'qpwgraph', 'qpwgraph ', '/usr/share/icons/hicolor/32x32/apps/org.rncbc.qpwgraph.png' },
  { 'vokoscreenNG', 'vokoscreenNG', '/usr/share/icons/hicolor/256x256/apps/vokoscreenNG.png' },
}

local menuee69799670a33f75d45c57d1d1cd0ab3 = {
  { 'AMDGPU TOP (GUI)', 'amdgpu_top --gui' },
  { 'AQEMU', 'aqemu' },
  { 'Android File Transfer (MTP)', 'android-file-transfer' },
  { 'Avahi Zeroconf Browser', '/usr/bin/avahi-discover' },
  { 'BleachBit', 'bleachbit', '/usr/share/pixmaps/bleachbit.png' },
  { 'Btrfs Assistant', 'btrfs-assistant-launcher' },
  { 'CPU-X', 'cpu-x' },
  { 'Contour', 'contour', '/usr/share/icons/hicolor/32x32/apps/org.contourterminal.Contour.png' },
  { 'Dolphin', 'dolphin ' },
  { 'Fcitx', 'fcitx', '/usr/share/icons/hicolor/16x16/apps/fcitx.png' },
  { 'Fcitx 5', '/usr/bin/fcitx5', '/usr/share/icons/hicolor/16x16/apps/fcitx.png' },
  { 'Fnott', 'fnott' },
  { 'GPU-Viewer', 'gpu-viewer' },
  { 'GParted', '/usr/bin/gparted ', '/usr/share/icons/hicolor/16x16/apps/gparted.png' },
  { 'Ghostty', 'ghostty', '/usr/share/icons/hicolor/16x16/apps/com.mitchellh.ghostty.png' },
  { 'HP-Scan', '/usr/bin/hp-uiscan', '///home/hebedite/.local/share/icons/Gruvbox-Plus-Dark/apps/scalable/hp.svg' },
  { 'Hardware Locality lstopo', 'lstopo' },
  { 'Htop', 'xterm -e htop', '///home/hebedite/.local/share/icons/Gruvbox-Plus-Dark/apps/scalable/htop.svg' },
  { 'KDE Partition Manager', 'partitionmanager' },
  { 'LSHW', '/usr/sbin/gtk-lshw', '///home/hebedite/.local/share/icons/Gruvbox-Plus-Dark/apps/scalable/gtk-lshw.svg' },
  { 'Manage Printing', 'xdg-open http://localhost:631/', '/usr/share/icons/hicolor/16x16/apps/cups.png' },
  { 'OpenJDK Java 21 Console', '/usr/lib/jvm/java-21-openjdk/bin/jconsole' },
  { 'OpenJDK Java 21 Shell', 'xterm -e /usr/lib/jvm/java-21-openjdk/bin/jshell' },
  { 'Radeon Profile', 'radeon-profile', '/usr/share/pixmaps/radeon-profile.png' },
  { 'Rio', 'rio', '///home/hebedite/.local/share/icons/rio.svg' },
  { 'Thunar File Manager', 'thunar ', '/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png' },
  { 'Timeshift', 'timeshift-launcher', '/usr/share/icons/hicolor/16x16/apps/timeshift.png' },
  { 'Virtual Machine Manager', 'virt-manager', '/usr/share/icons/hicolor/16x16/apps/virt-manager.png' },
  { 'Warehouse', 'warehouse' },
  { 'Waycheck', 'waycheck' },
  { 'WezTerm', 'wezterm start --cwd .', '///home/hebedite/.local/share/icons/mycons/scalable/WezPink-1024x1024.png' },
  { 'Zellij', 'xterm -e zellij', '/usr/share/pixmaps/zellij.png' },
  { 'conky', 'conky --daemonize --pause=1' },
  { 'coppwr', 'coppwr', '/usr/share/icons/hicolor/32x32/apps/io.github.dimtpap.coppwr.png' },
  { 'fish', 'xterm -e fish', '/usr/share/pixmaps/fish.png' },
  { 'kitty', 'kitty', '///home/hebedite/.local/share/icons/Gruvbox-Plus-Dark/apps/scalable/kitty.svg' },
  { 'lf', 'xterm -e lf' },
  { 'nvtop', 'xterm -e nvtop', '/usr/share/icons/nvtop.svg' },
  { 'nwg-processes', 'nwg-processes', '/usr/share/pixmaps/nwg-processes.svg' },
  { 'xplr', 'xterm -e xplr', '/usr/share/icons/hicolor/16x16/apps/xplr.png' },
}

xdgmenu = {
  { 'Accessibility', menue0e4fc6213e8b3593495a7260c3a4c2e },
  { 'Accessories', menu98edb85b00d9527ad5acebe451b3fae6 },
  { 'Education', menude7a22a0c94aa64ba2449e520aa20c99 },
  { 'Games', menu251bd8143891238ecedc306508e29017 },
  { 'Graphics', menud334dfcea59127bedfcdbe0a3ee7f494 },
  { 'Internet', menuc8205c7636e728d448c2774e6a4a944b },
  { 'Office', menudf814135652a5a308fea15bff37ea284 },
  { 'Other', menu6311ae17c1ee52b36e68aaf4ad066387 },
  { 'Programming', menue6f43c40ab1c07cd29e4e83e4ef6bf85 },
  { 'Science & Math', menu80d754c83abbbd4ef5d150904efcc86c },
  { 'Sound & Video', menu52dd1c847264a75f400961bfb4d1c849 },
  { 'System Tools', menuee69799670a33f75d45c57d1d1cd0ab3 },
}
