---@meta GLib

---@alias OS_INFO_KEY
--- |"BUG_REPORT_URL" The URL of the OS’s bug reporting page.
--- |"DOCUMENTATION_URL" The URL of the OS’s documentation.
--- |"HOME_URL" The URL of the OS’s home page.
--- |"ID" The ID of the OS.
--- |"NAME" The name of the OS.
--- |"PRETTY_NAME" The human-readable name of the OS.
--- |"PRIVACY_POLICY_URL" The URL of the OS’s privacy policy page.
--- |"SUPPORT_URL" The URL of the OS’s support page.
--- |"VERSION" The version of the OS.
--- |"VERSION_CODENAME" The version codename of the OS.
--- |"VERSION_ID" The version ID of the OS.
--- | string Any other key.

---@alias UserDirectory
--- | "DIRECTORY_DESKTOP" The user’s Desktop directory.
--- | "DIRECTORY_DOCUMENTS" The user’s Documents directory.
--- | "DIRECTORY_DOWNLOAD" The user’s Downloads directory.
--- | "DIRECTORY_MUSIC" The user’s Music directory.
--- | "DIRECTORY_PICTURES" The user’s Pictures directory.
--- | "DIRECTORY_PUBLIC_SHARE" The user’s shared directory.
--- | "DIRECTORY_TEMPLATES" The user’s Templates directory.
--- | "DIRECTORY_VIDEOS" The user’s Movies directory.

---@alias FormatSizeFlags
--- | "FORMAT_SIZE_BITS" Set the size as a quantity in bits, rather than bytes, and return units in bits. For example, ‘Mbit’ rather than ‘MB’.
--- | "FORMAT_SIZE_DEFAULT" Default format. Behave the same as g_format_size()
--- | "FORMAT_SIZE_IEC_UNITS" Use IEC units (Ki, Mi, Gi, etc.). Use IEC (base 1024) units with “KiB”-style suffixes. IEC units should only be used for reporting things with a strong “power of 2” basis, like RAM sizes or RAID stripe sizes. Network and storage sizes should be reported in the normal SI units.
--- | "FORMAT_SIZE_LONG_FORMAT" Include the exact number of bytes as part of the returned string. For example, “45.6 kB (45,612 bytes)”.
--- | "FORMAT_SIZE_ONLY_UNIT" Return only unit, without value; this should not be used together with G_FORMAT_SIZE_LONG_FORMAT nor G_FORMAT_SIZE_ONLY_VALUE. Since: 2.74
--- | "FORMAT_SIZE_ONLY_VALUE" Return only value, without unit; this should not be used together with G_FORMAT_SIZE_LONG_FORMAT nor G_FORMAT_SIZE_ONLY_UNIT. Since: 2.74

---@class GLib
---@field Bytes GBytesStatic
---The directory separator as a string. This is “/” on UNIX machines and “\" under Windows.
---@field DIR_SEPARATOR_S string
---@field Error ErrorStatic
---@field FormatSizeFlags FlagsDefinition<FormatSizeFlags>
---@field MainContextFlags FlagsDefinition<MainContextFlags>
---@field MainLoop MainLoopStatic
---@field PRIORITY_DEFAULT 0
---@field PRIORITY_DEFAULT_IDLE 200
---@field PRIORITY_HIGH -100
---@field PRIORITY_HIGH_IDLE 100
---@field PRIORITY_LOW 300
---The search path separator as a string. This is “:” on UNIX machines and “;” under Windows.
---@field SEARCHPATH_SEPARATOR_S string
---@field SeekType EnumDefinition<SeekType>
---@field Source SourceStatic
---@field UserDirectory EnumDefinition<UserDirectory | "N_DIRECTORIES">
---@field Variant VariantStatic
---@field VarientType VarientTypeStatic
---@field build_filenamev fun(args: string[]): string
---@field build_pathv fun(separator: string, args: string[]): string
---Symlinks are not followed. No IO is done.
---See https://docs.gtk.org/glib/func.canonicalize_filename.html
---@field canonicalize_filename fun(filename: string, relative_to: string?): string
---@field chdir fun(path: string): 0|-1
---Returns nil if the version is compatible, otherwise returns a string describing the incompatibility.
---@field check_version fun(required_major: integer, required_minor: integer, required_micro: integer): string?
---@field chmod fun(filename: string, mode: number): 0|-1
---@field find_program_in_path fun(prog: string): string?
---See format_size_full for more information and flags.
---@field format_size fun(size: integer): string
---Formats a size (for example the size of a file) into a human readable
---string. Sizes are rounded to the nearest size prefix (kB, MB, GB) and are
---displayed rounded to the nearest tenth.
---@field format_size_full fun(size: integer, flags: Flags<FormatSizeFlags>): string
---@field get_current_dir fun(): string
---@field get_home_dir fun(): string
---@field get_tmp_dir fun(): string
---@field get_host_name fun(): string
---returns g_get_language_names_with_category(“LC_MESSAGES”).
---@field get_language_names fun(): string[]
---This function consults the environment variables LANGUAGE, LC_ALL,
---category_name, and LANG to find the list of locales specified by the user.
---@field get_language_names_with_category fun(category: string): string[]
---The monotonic time, in microseconds.
---@field get_monotonic_time fun(): number
---Determine the approximate number of threads that the system will schedule
---simultaneously for this process.
---@field get_num_processors fun(): integer
---@field get_os_info fun(key: OS_INFO_KEY): string?
---Gets the real name of the user. If the real user name cannot be determined,
---the string “Unknown” is returned.
---@field get_real_name fun(): string
---The number of microseconds since January 1, 1970 UTC.
---@field get_real_time fun(): number
---@field get_user_cache_dir fun(): string
---@field get_user_config_dir fun(): string
---@field get_user_data_dir fun(): string
---@field get_user_name fun(): string
---@field get_user_runtime_dir fun(): string
---Returns the full path of a special directory using its logical id.
---On UNIX this is done using the XDG special user directories. For
---compatibility with existing practise, G_USER_DIRECTORY_DESKTOP falls back to
---$HOME/Desktop when XDG special user directories have not been set up.
---@field get_user_special_dir fun(directory: Enum<UserDirectory>): string?
---@field get_user_state_dir fun(): string
---@field getenv fun(variable: string): string?
---Adds a function to be called whenever there are no higher priority events
---pending. If the function returns G_SOURCE_REMOVE or FALSE it is
---automatically removed from the list of event sources and will not be called
---again.
---Remove with `GLib.Source.remove(id)`.
---@field idle_add fun(priority: integer, function: SourceFunc): id: integer
---@field listenv fun(): string[]
---Note, null-embedded strings are not supported.
---@field markup_escape_text fun(text: string, length: number): string
---@field mkdir fun(pathname: string, mode: number): 0|-1
---Return 0 if the directory already exists, or was successfully created. Returns -1 if an error occurred, with errno set.
---@field mkdir_with_parents fun(pathname: string, mode: number): 0|-1
---If file_name ends with a directory separator it gets the component before the last slash.
---@field path_get_basename fun(path: string): string
---If the file name has no directory components “.” is returned
---@field path_get_dirname fun(path: string): string
---Returns TRUE if the given file_name is an absolute file name. Note that this is a somewhat vague concept on Windows.
---@field path_is_absolute fun(path: string): boolean
---Returns a pointer into file_name after the root component, i.e. after the “/” in UNIX or “C:" under Windows. If file_name is not an absolute path it returns NULL.
---@field path_skip_root fun(file_name: string): string?
---@field random_double fun(): number
---@field random_double_range fun(begin: number, end: number): number
---@field random_int fun(): integer
---@field random_int_range fun(begin: integer, end: integer ): integer
---Sets the seed for the global random number generator, which is used by the g_random_* functions, to seed.
---@field random_set_seed fun(seed: integer)
---Resets the cache used for g_get_user_special_dir(), so that the latest
---on-disk version is used. Call this only if you just changed the data on disk
---yourself.
---@field reload_user_special_dirs_cache fun()
---@field rmdir fun(filename: string): 0|-1
---@field setenv fun(var: string, val: string, overwrite: boolean): boolean
---@field shell_quote fun(unquoted_string: string): string
---@field shell_unquote fun(quoted_string: string): string?, Error?
---@field shell_parse_argv fun(command_line: string): string[]|false, Error?
---Gets the smallest prime number from a built-in array of primes which is
---larger than num. The built-in array of primes ranges from 11 to 13845163
---such that each prime is approximately 1.5-2 times the previous prime.
---@field spaced_primes_closest fun(num: integer): integer
---interval is in milliseconds. The function is called repeatedly until it
---returns false, at which point the timeout is automatically destroyed and the
---function will not be called again.
---@field timeout_add fun(priority: integer, interval: integer, function: SourceFunc): id: integer
---Note that the first call of the timer may not be precise for timeouts of one
---second. If you need finer precision and have such a timeout, you may want to
---use g_timeout_add() instead.
---@field timeout_add_seconds fun(priority: integer, interval: integer, function: SourceFunc): id: integer
---@field unsetenv fun(var: string)
---@field close fun(fd: integer): boolean, Error?
---@field base64_encode fun(data: string): string?
---@field base64_decode fun(data: string): string?
