---@meta Gio

---@class Gio.FileDescriptorBased
---@field get_fd fun(self: Gio.FileDescriptorBased): integer

---@class Gio
---@field AppInfo Gio.AppInfo
---@field Async Gio.Async
---@field BufferedInputStream Gio.BufferedInputStream
---@field BusType EnumDefinition<Gio.DBusType>
---@field Cancellable Gio.Cancellable
---@field Credentials Gio.Credentials
---@field DataInputStream Gio.DataInputStream
---@field DBusAuthObserver Gio.DBusAuthObserver
---@field DBusCallFlags FlagsDefinition<Gio.DBusCallFlags>
---@field DBusConnection Gio.DBusConnection
---@field DBusConnectionFlags FlagsDefinition<Gio.DBusConnectionFlags>
---@field DBusMessage Gio.DBusMessage
---@field DBusMessageFlags FlagsDefinition<Gio.DBusMessageFlags>
---@field DBusSendMessageFlags FlagsDefinition<Gio.DBusSendMessageFlags>
---@field DBusSignalFlags FlagsDefinition<Gio.DBusSignalFlags>
---@field DesktopAppInfo Gio.DesktopAppInfo
---@field FileCreateFlags Gio.FileCreateFlags
---@field File Gio.File
---@field FileCopyFlags FlagsDefinition<Gio.FileCopyFlags>
---@field FileCreateFlags FlagsDefinition<Gio.FileCreateFlags>
---@field FileInfo Gio.FileInfo
---@field FileMonitorEvent EnumDefinition<Gio.FileMonitorEvent>
---@field FileMonitorFlags FlagsDefinition<Gio.FileMonitorFlags>
---@field FileQueryInfoFlags FlagsDefinition<Gio.FileQueryInfoFlags>
---@field FileType EnumDefinition<Gio.FileType>
---@field FilterInputStream Gio.FilterInputStream
---@field Icon Gio.Icon
---@field InputStream Gio.InputStream
---@field IOErrorEnum EnumDefinition<string>
---@field MemoryInputStream Gio.MemoryInputStream
---@field Seekable Gio.Seekable
---@field Settings Gio.Settings
---@field Subprocess Gio.Subprocess
---@field SubprocessFlags FlagsDefinition<Gio.SubprocessFlags>
---@field SubprocessLauncher Gio.SubprocessLauncher
---@field UnixInputStream Gio.UnixInputStream
---@field UnixOutputStream Gio.UnixOutputStream
---@field FILE_ATTRIBUTE_STANDARD_DISPLAY_NAME 'standard::display-name'
---@field FILE_ATTRIBUTE_STANDARD_NAME 'standard::name'
---@field FILE_ATTRIBUTE_STANDARD_SIZE 'standard::size'
---@field FILE_ATTRIBUTE_STANDARD_TYPE 'standard::type'
---@field bus_get fun(bus_type: Enum<Gio.DBusType>, cancellable?: Gio.Cancellable, callback: Gio.AsyncReadyCallback<Gio.DBusConnection>)
---@field bus_get_finish fun(res: Gio.AsyncResult): Gio.DBusConnection
---@field bus_get_sync fun(bus_type: Enum<Gio.BusType>, cancellable?: Gio.Cancellable): Gio.DBusConnection

local lgi = require 'lgi' ---@type lgi
return lgi.Gio
