---@class GBytesStatic
---@operator call(string): GBytes
---@field new fun(content: string): GBytes

---@class GBytes
---@field compare fun(self: GBytes, other: GBytes): integer
---@field data string?
---@field equal fun(self: GBytes, other: GBytes): boolean
---@field get_data fun(self: GBytes): string?
---@field get_region fun(self: GBytes, element_size: integer, offset: integer, n_elements: integer): userdata # Currently unusable in lua
---@field get_size fun(self: GBytes): integer
---@field hash fun(self: GBytes): integer
---@field new_from_bytes fun(self: GBytes, offset: integer, length: integer): GBytes
